### ISSUE TITLE
Unclear setup of own colorschemes

### ISSUE THREAD

**Issue by koopa1338** [tjdevries/colorbuddy.nvim#5]
The README shows some example themes but it lacks some information about how to setup your own colorscheme:

- where do I define the colors?
- do I have to include them and if so where and how?
- how do I select my new colorscheme?
- are there any vim settings required

My naive try was:

1. install the Plugin and load it via `packadd`
2. create a `nvim/lua/colors.lua` file and define my colorscheme
3. require that file in my `init.lua`

→ didn't work, for some reason my colors are broken but I don't get any error messages.

**Comment by rockerBOO** [comment]
I just made a simple colorscheme. So I think you got it for the most part but requiring the file runs into caching problems. I found if i had it return from the module it works better. So for example instead of JUST requiring, make the module return a function that you can call to set the color scheme.

https://github.com/rockerBOO/boo-colorscheme-nvim/blob/main/lua/boo-colorscheme.lua#L8

And then I have 
```
lua require'boo-colorscheme'.use{}
```

**Comment by redbug312** [comment]
@rockerBOO I was searching for the caching problem and found a solution. It seems `require` won't load the same file, as explained in [nvim-lua-guide#1](https://github.com/nanotee/nvim-lua-guide/issues/1).

Loaded info must be removed to make `:colorscheme` force-reload, so I've done this in [colors/cactusbuddy.vim](https://github.com/RedBug312/cactusbuddy/blob/master/colors/cactusbuddy.vim) of my colorscheme.

```viml
lua package.loaded.cactusbuddy = nil
lua require('cactusbuddy')
```

**Comment by thepenguinthatwants** [comment]
I think this seriously needs a documentation as this might become way more popular if it gives sense how to use it.

**Comment by tjdevries** [comment]
Should be just `colorscheme blah` now and load it with lua, i included example one in repo now as well :)
